### ISSUE TITLE
Export command doesn't honour --mode flag

### ISSUE THREAD

**Issue by dsimansk** [knative/client#1087]
### Bug report

When `--mode` flag is specified for ksvc without `--with-revisions` flag that output format is plain Knative Service yaml instead of our custom `Export` type.

```
➜  ~ kn service export hello -o yaml --mode export                 
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: docker.io/dsimansk/helloworld
      creationTimestamp: null
      name: hello-djrrc-1
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: TARGET
          value: v1
        image: docker.io/dsimansk/helloworld
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}

```
### Expected behavior

`kn service export hello -o yaml --mode export` - output is printed in requested `Export` format.

### Steps to reproduce the problem

Exec and check the format.
```
 kn service export hello -o yaml --mode export                 
```

### kn version

HEAD

### Knative (serving/eventing) version

> Nightly

/kind good-first-issue
