### ISSUE TITLE
How to delete a broker? 

### ISSUE THREAD

**Issue by snowwolf007cn** [knative/client#1403]
I'm using docker desktop for mac k8s cluster.

I start a kafka using docker compose:
```yaml
version: "3.8"
services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - '2181:2181'
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
```
I create a configmap in namespace iacallback-eventing as below:
```
apiVersion: v1
data:
  bootstrap.servers: docker.for.mac.localhost:9092
  default.topic.partitions: "10"
  default.topic.replication.factor: "3"
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: iacallback-eventing
  labels:
    kafka.eventing.knative.dev/release: devel
```
I created a Kafka broker us kn:
```shell
kn broker create iacallback-broker -n iacallback-eventing
```

something wrong 
and I deleted it:
```shell
kn broker delete iacallback-broker -n iacallback-eventing 
```

I was told it succeed:
```shell
Broker 'iacallback-broker' successfully deleted in namespace 'iacallback-eventing'.
```

But when I can still see it in the list.

How to delete the broker?
