### ISSUE TITLE
add support for setting containerConcurency

### ISSUE THREAD

**Issue by duglin** [knative/client#151]
It would be nice to be able to set the `containerConcurrency` field via `kn`:
```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: ${APP_IMAGE}
          containerConcurrency: 1
```
See last line.

Something like `--max-concurrency=1`
