### ISSUE TITLE
Create broker object with spec.config pointer

### ISSUE THREAD

**Issue by matzew** [knative/client#1525]
### Feature request

There is currently no option to use `kn` to create a broker and provide `config` parts (e.g. ponting to a ConfigMap or an other resource)

Something like below needs to be still created using `k apply...` :

```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: my-kafka-broker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing
```

### UI Example

```

```

**Comment by rhuss** [comment]
the `config:` field can point to any object ? Would it be good enough that `kn` supports only `ConfigMaps` as references ? That would make the UI much easier (e.g. `--config kafka-broker-config`)

**Comment by matzew** [comment]
It;s a duck, and can be anything:
https://github.com/knative/eventing/blob/main/pkg/apis/eventing/v1/broker_types.go#L71-L75

As the Rabbit impl goes, it leverages their own CRDs:
https://github.com/knative-sandbox/eventing-rabbitmq/tree/main/samples/broker/dlq#create-the-rabbitmq-broker

e.g.:
```yaml
...
  spec:
    config:
      apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      name: rokn
...
```
