### ISSUE TITLE
kn does not show new trigger filters

### ISSUE THREAD

**Issue by pnivanov** [knative/client#1785]
I am using the Knative Eventing new trigger filters feature:
https://knative.dev/docs/eventing/experimental-features/new-trigger-filters/

```yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display-trigger
spec:
  broker: default
  filters:
    - cesql: "LOWER(type) = 'my-event-type'"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
```

I noticed that `kn trigger describe` does not output the new `filters` data.
```
kn trigger describe event-display-trigger
Name:         event-display-trigger
Namespace:    default
Labels:       eventing.knative.dev/broker=default
Annotations:  eventing.knative.dev/creator=kubernetes-admin, eventing.knative.dev/lastModifier=ku ...
Age:          13h
Broker:       default

Sink:        
  Name:      event-display
  Resource:  Service (serving.knative.dev/v1)

Conditions:  
  OK TYPE                      AGE REASON
  ++ Ready                     13h 
  ++ BrokerReady               13h 
  ++ DeadLetterSinkResolved    13h DeadLetterSinkNotConfigured
  ++ DependencyReady           13h 
  ++ SubscriberResolved        13h 
  ++ SubscriptionReady         13h 
```

I know that this is still an alpha feature, so I don't know if this is a feature request or a bug.
I would expect when the feature is enabled to see the filters.
