### ISSUE TITLE
Option --limits-memory doesnt bring up the app

### ISSUE THREAD

**Issue by VeerMuchandi** [knative/client#294]
## In what area(s)?

> /kind good-first-issue 

## What version of Knative Client?

$ kn version
Version:      v0.2.0
Build Date:   2019-07-10 20:57:03
Git Revision: e1614f9
Dependencies:
- serving:    v0.6.0

## What version of Knative Serving running on your cluster?

> 0.6.x

## Expected Behavior

`kn service create SERVICENAME --image=IMAGE --limits-memory=500m`

is supposed to create the service

## Actual Behavior

Waits and times out. 

See below:

```
$ kn service create tasks-sl --image=image-registry.openshift-image-registry.svc:5000/gartner1/tasks --limits-memory=500m
Service 'tasks-sl' successfully created in namespace 'gartner1'.
Waiting for service 'tasks-sl' to become ready ... 
timeout: service 'tasks-sl' not ready after 60 seconds
```

status in the service
```
status:
  conditions:
  - lastTransitionTime: "2019-07-24T19:53:35Z"
    status: Unknown
    type: ConfigurationsReady
  - lastTransitionTime: "2019-07-24T19:53:35Z"
    message: The Route is still working to reflect the latest desired specification.
    reason: OutOfDate
    status: Unknown
    type: Ready
  - lastTransitionTime: "2019-07-24T19:53:34Z"
    message: The Route is still working to reflect the latest desired specification.
    reason: OutOfDate
    status: Unknown
    type: RoutesReady
  latestCreatedRevisionName: tasks-sl-q4btw
  observedGeneration: 1
```

## Steps to Reproduce the Problem

create a service with `--limits-memory`
