### ISSUE TITLE
Apply traffic/tag flags only if configuration update pass

### ISSUE THREAD

**Issue by navidshaikh** [knative/client#374]
## Expected Behavior 
Given traffic/tag flags along with configuration update flags, traffic/tag flags should be applied only if configuration update passes. If configuration update fails, do not apply traffic spec.

## Actual Behavior
We apply the configuration update flags and traffic/tag flags to service and then update the service at once. If given configuration update flags fail to generate a ready revision for service, and traffic/tag flags refer to it, request is interpreted incorrectly.  This also brings uncertainty for further traffic operations.

## Steps to Reproduce the Problem
1. Create a new service
```
➜  kn service create svc --image docker.io/swordphilic/go-helloworld
Service 'svc' successfully created in namespace 'default'.
Waiting for service 'svc' to become ready ... OK

Service URL:
http://svc.default.apps-crc.testing
```

2. Check revisions
```
➜  kn revision list -s svc                                     
NAME          SERVICE   GENERATION   AGE   CONDITIONS   READY   REASON
svc-qlfgh-1   svc       1            53s   4 OK / 4     True    
```

3. Update service with configuration flags which should create a ready revision and
 tag it with latest and 10% traffic, tag earlier revision as candidate and 90%.
```
➜  kn service update svc --env TARGET=kn --tag @latest=latest,svc-qlfgh-1=candidate --traffic latest=10,candidate=90
Waiting for service 'svc' to become ready ... OK
Service 'svc' updated in namespace 'default'.
```

4. Check revisions
```
➜  kn revision list -s svc                                                                                          
NAME          SERVICE   GENERATION   AGE    CONDITIONS   READY   REASON
svc-gmzcq-2   svc       2            18s    4 OK / 4     True    
svc-qlfgh-1   svc       1            2m2s   3 OK / 4     True    
```

5. Check if traffic spec and status matches. Result = matches
```
➜  kn service describe svc -o yaml | tail -n 36
  traffic:
  - latestRevision: true
    percent: 10
    tag: latest
  - latestRevision: false
    percent: 90
    revisionName: svc-qlfgh-1
    tag: candidate
status:
  address:
    url: http://svc.default.svc.cluster.local
  conditions:
  - lastTransitionTime: "2019-08-17T11:29:23Z"
    status: "True"
    type: ConfigurationsReady
  - lastTransitionTime: "2019-08-17T11:29:24Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2019-08-17T11:29:24Z"
    status: "True"
    type: RoutesReady
  latestCreatedRevisionName: svc-gmzcq-2
  latestReadyRevisionName: svc-gmzcq-2
  observedGeneration: 2
  traffic:
  - latestRevision: true
    percent: 10
    revisionName: svc-gmzcq-2
    tag: latest
    url: http://latest-svc.default.apps-crc.testing
  - latestRevision: false
    percent: 90
    revisionName: svc-qlfgh-1
    tag: candidate
    url: http://candidate-svc.default.apps-crc.testing
  url: http://svc.default.apps-crc.testing
```

6. Update service with incorrect configuration flags which would yield a failed revision, update tags and set 10% to latest and 90% to previous (note the revision names)

```
➜  kn service update svc --image does.not/exist --untag latest,candidate --tag @latest=latest,svc-gmzcq-2=candidate --traffic latest=10,candidate=90
Waiting for service 'svc' to become ready ... 
RevisionFailed: Revision "svc-sqhwn-3" failed with message: Unable to fetch image "does.not/exist": Get https://does.not/v2/: dial tcp: lookup does.not on 172.30.0.10:53: no such host.
```

7. Check the traffic spec and traffic status.
```
➜  kn service describe svc -o yaml | tail -n 44
  traffic:
  - latestRevision: true
    percent: 10
    tag: latest
  - latestRevision: false
    percent: 90
    revisionName: svc-gmzcq-2
    tag: candidate
status:
  address:
    url: http://svc.default.svc.cluster.local
  conditions:
  - lastTransitionTime: "2019-08-17T11:33:54Z"
    message: 'Revision "svc-sqhwn-3" failed with message: Unable to fetch image "does.not/exist":
      Get https://does.not/v2/: dial tcp: lookup does.not on 172.30.0.10:53: no such
      host.'
    reason: RevisionFailed
    status: "False"
    type: ConfigurationsReady
  - lastTransitionTime: "2019-08-17T11:33:54Z"
    message: 'Revision "svc-sqhwn-3" failed with message: Unable to fetch image "does.not/exist":
      Get https://does.not/v2/: dial tcp: lookup does.not on 172.30.0.10:53: no such
      host.'
    reason: RevisionFailed
    status: "False"
    type: Ready
  - lastTransitionTime: "2019-08-17T11:33:54Z"
    status: "True"
    type: RoutesReady
  latestCreatedRevisionName: svc-sqhwn-3
  latestReadyRevisionName: svc-gmzcq-2
  observedGeneration: 3
  traffic:
  - latestRevision: true
    percent: 10
    revisionName: svc-gmzcq-2
    tag: latest
    url: http://latest-svc.default.apps-crc.testing
  - latestRevision: false
    percent: 90
    revisionName: svc-gmzcq-2
    tag: candidate
    url: http://candidate-svc.default.apps-crc.testing
  url: http://svc.default.apps-crc.testing
```

In step 7 output, note `status.traffic` reports two targets, each pointing to same revision `svc-gmzcq-2` with 10 and 90% traffic portions with tags latest and candidate pointing to same revision. This is different than what's requested on the command. If configuration update has to fail, kn should not process the traffic flags at all.

Although this can be recovered by setting the correct image in subsequent operation as below
```
➜ kn service update svc --image docker.io/swordphilic/go-helloworld --untag latest,candidate --tag @latest=latest,svc-gmzcq-2=candidate --traffic latest=10,candidate=90
```
and kn brings back the desired-spec and actual-status in sync.

However, after performing step 6, service's spec.traffic and status.traffic is different (as seen in step 7 output), we could've avoided that, if we didn't set the traffic before knowing configuration update status.

If used `--async` flag, we'll bring this inconsistencies again even if fix suggested is applied, we should default to synchronous update of service if user requests traffic/tag related operations.
