### ISSUE TITLE
kn source describe-type - show details of a certain source type

### ISSUE THREAD

**Issue by sixolet** [knative/client#497]
This command describes the source type CRDs, as described in the [MVP doc](https://docs.google.com/document/d/1B8VK-5nuxt3D-i1Up3onmUbzcztQXE0GRgf1lfx49P8/edit#heading=h.qns5zgif37wk) : 

```
# List the specifics about a source type (built-in / plugin)
kn source describe-type apiserver
Name:         apiserversource.sources.eventing.knative.dev
Kind:         ApiServerSource
Labels:       eventing.knative.dev/source=true
          eventing.knative.dev/release=devel
              knative.dev/crd-install: true
Annotations:  ....
Age:          12d

Event-Types:
  addResource=dev.knative.apiserver.resource.add
  deleteResource=dev.knative.apiserver.resource.delete
  ...
Configuration:
  ...
```

For Source types which have built-in or plugin support an individual and source-specific output can be created, which differs from source to source. The example above is just illustrative and should be fine-tuned for each individual source. It could also carry additional commands like --verbose or --debug like in kn service describe.

For sources of a generic type, a generic output is created. The type to specify is a [guessable CRD name](https://docs.google.com/document/d/1B8VK-5nuxt3D-i1Up3onmUbzcztQXE0GRgf1lfx49P8/edit#bookmark=id.9aoo4s1jnj03). Generic types are considered as a fallback only (i.e if there is no typed source support with the same name). The full CRD name can be specified to force the usage of the generic source output.

The output includes the event types that the source is capable of generating as well as the configuration used to create an instance of the source. Note that it only includes the first level of configuration information, so this will work better for sources that have very flat specs and poorly for those with nested specs.

```yaml
# List the specifics about a source type (generic)
kn source describe-type storage
Name:         storages.events.cloud.run
Kind:         Storage
Version:       events.cloud.run/v1alpha1
Labels:       eventing.knative.dev/source=true
              events.cloud.run/crd-install=true
              events.cloud.run/release=devel
Annotations:  ....
Age:          12d

Event Types:
  archive=google.storage.object.archive
  delete=google.storage.object.delete
     ….
Configuration:
  Required:
    sink
      Type: object
      Description: Where to sink the notifications to.
    gcsSecret
      Type: object
      Description: Credential to use for creating a GCP notification. Must be a service account key in JSON format (see https://cloud.google.com/iam/docs/creating-managing-service-account-keys).
    bucket
      Type: string
      Description: GCS bucket to subscribe to. For example my-test-bucket
  Optional:
    pullSubscriptionSecret
      Type: object
      Description: Optional credential to use for subscribing to the GCP PubSub topic. If omitted, uses gcsCredsSecret. Must be a service account key in JSON format (see https://cloud.google.com/iam/docs/creating-managing-service-account-keys).
    objectNamePrefix
      Type: string
      Description: Optional prefix to only notify when objects match this prefix.
    serviceAccountName
      Type: string
      Description: Service Account to run Receive Adapter as. If omitted, uses 'default'.
    project
      Type: string
      Description: Google Cloud Project ID to create the scheduler job in.
    eventTypes
      Type: array
    payloadFormat
      Type: string
      Description: Optional payload format. Either NONE or JSON_API_V1. If omitted, uses JSON_API_V1.
```

Note that this generic output is often overwhelming and hard to read. 
There are efforts on the way which try to simplify this by adding Metadata to the CRD which provides a mapping from flat CLI options to deeper nested fields within a CRD’s schema. Refer to these issues for further discussion:

* https://github.com/kubernetes/kubernetes/issues/82942 about to support `x-` style schema specification extensions in CRDs (which would be the perfect spot to hold the mapping metadata)
* https://github.com/knative/eventing/issues/1940 for a general discussion how to add this meta data to Source CRDs. If OpenAPI schema mechanism can’t be used then annotations are probably the second best choice.

It is expected that eventually this flat CLI option to schema mapping will affect the output of kn source describe  for the generic case considerably.
