### ISSUE TITLE
Add flag "auto-service-account" to apiserver source

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/client#572]
/kind feature

## Describe the feature:

ApiServerSource depends on a valid service account. In order to create an ApiServerSource, a service account must be created, like this:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-sa-watcher
rules:
  - apiGroups:
      - <api group>
    resources:
      - <resources>
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-sa-event-watcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-sa-watcher
subjects:
  - kind: ServiceAccount
    name: service-sa
    namespace: default
```

It is complicate if the user doesn't know how to provide a valid service-account-name. So except that he/she uses an existing service account name, the user needs two steps to enable an apiserver source: <step 1> create a valid service account name, <step 2> create an apiserver source.

My proposal is to add a flag `auto-service-account` to `kn source apiserver create`. If users input `kn source apiserver create --auto-service-account=true`, a minimal ClusterRole will be created and used for the apiserver source.
