### ISSUE TITLE
pick up default namespace from .kube/config instead of hardcoding it in kn

### ISSUE THREAD

**Issue by cppforlife** [knative/client#7]

**Comment by rhuss** [comment]
Maybe also add a global `--namespace` option for specifying the namespace to operate on.

**Comment by maximilien** [comment]
I like @rhuss suggestion.

@cppforlife can you elaborate on your title? Or is it simply reading the current `~/.kube/config` and getting the namespace from the first `context` section. So in my case the namespace `default` from:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: [redacted]
    server: [redacted]
  name: knative-demo
contexts:
- context:
    cluster: knative-demo
    namespace: default #<---- this namespace
    user: maxim@us.ibm.com
  name: knative-demo
current-context: knative-demo
kind: Config
...
```
