### ISSUE TITLE
"kn service export --with-revisions" should create revision COs directly

### ISSUE THREAD

**Issue by rhuss** [knative/client#728]
Currently, `kn service export --with-revisions` exports only services which are update one after each other. However, as it is allowed to create revisions directly it makes more sense to export those directly, with the proper owner-references.

An `kn service import` then could then also adapt the revision names in case of collisions.

**Comment by itsmurugappan** [comment]
@rhuss looked at this today. 
When we do ```kn service export --with-revisions ```. We would have to export the service and all the active revisions.
When we import using kn import, we would have to get owner uid (of the configuration) after creating the service , plug into revision and create it. 
With this approach, Kubectl apply would not work directly. User has to plugin ownerid manually  and use kubectl apply.
Is that right ? am i missing something ?

**Comment by rhuss** [comment]
> When we do `kn service export --with-revisions `. We would have to export the service and all the active revisions.

Correct.
 
> When we import using kn import, we would have to get owner uid (of the configuration) after creating the service , plug into revision and create it.
> With this approach, Kubectl apply would not work directly. User has to plugin ownerid manually and use kubectl apply.

Yes, that's correct. Sticking the owner-reference together properly is the task of `kn import`. 

However, we could also export the`Configuration`, too, so that we can set the owner reference already properly in the YAML file.  I think we should follow this path an export the full graph. Wdyt ?

**Comment by itsmurugappan** [comment]
I am not sure whether this is possible. Please see the below example. 
Exporting the service with 3 revisions will result in the below artifacts
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: envtest
  namespace: test-alpha
  uid: 08cd1946-97cf-4877-b1aa-1fe5d141f83f
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: murugappans/envtest:v1
      name: envtest-v3
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: greet
          value: vanakkam
        image: murugappans/envtest:v1
        name: user-container
        resources: {}
        securityContext:
          runAsUser: 1001
      timeoutSeconds: 300
  traffic:
  - latestRevision: false
    percent: 50
    revisionName: envtest-v1
  - latestRevision: false
    percent: 50
    revisionName: envtest-v2
---
apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  labels:
    serving.knative.dev/route: envtest
    serving.knative.dev/service: envtest
  name: envtest
  namespace: test-alpha
  ownerReferences:
  - apiVersion: serving.knative.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: envtest
    uid: 08cd1946-97cf-4877-b1aa-1fe5d141f83f
  uid: f68ddab9-f868-47ec-b405-829dd236270e
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: murugappans/envtest:v1
      name: envtest-v3
    spec:
      containerConcurrency: 0
      containers:
      - env:
        - name: greet
          value: vanakkam
        image: murugappans/envtest:v1
        name: user-container
        resources: {}
        securityContext:
          runAsUser: 1001
      timeoutSeconds: 300
---
apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  labels:
    serving.knative.dev/configuration: envtest
    serving.knative.dev/route: envtest
    serving.knative.dev/service: envtest
  name: envtest-v1
  namespace: test-alpha
  ownerReferences:
  - apiVersion: serving.knative.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Configuration
    name: envtest
    uid: f68ddab9-f868-47ec-b405-829dd236270e
spec:
  containerConcurrency: 0
  containers:
  - env:
    - name: greet
      value: hi
    image: murugappans/envtest:v1
    name: user-container
    resources: {}
    securityContext:
      runAsUser: 1001
  timeoutSeconds: 300
---
apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  labels:
    serving.knative.dev/configuration: envtest
    serving.knative.dev/route: envtest
    serving.knative.dev/service: envtest
  name: envtest-v2
  namespace: test-alpha
  ownerReferences:
  - apiVersion: serving.knative.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Configuration
    name: envtest
    uid: f68ddab9-f868-47ec-b405-829dd236270e
spec:
  containerConcurrency: 0
  containers:
  - env:
    - name: greet
      value: hola
    image: murugappans/envtest:v1
    name: user-container
    resources: {}
    securityContext:
      runAsUser: 1001
  timeoutSeconds: 300
```

When we create the service again , a new uid and a configuration will be generated, so the exported configuration cannot be used. Now the uid in owner references of the revision has to be changed to the newly generated configuration. 

With that being said we can export the service and the revisions and kn import can handle the owner references. This will result in only one pod starting.

With the current approach of exporting services, more pods will be created but it can be used by kubectl also and the generation number will be clean.
