### ISSUE TITLE
Introduce "KnExport" type for defining an export format.

### ISSUE THREAD

**Issue by rhuss** [knative/client#824]
### Feature request

We have now `kn service export` which supports two modes for exporting revision: One which is directly usable with `kubectl` and uses a kind of "replay of services" to build up the service-configuration-revision graph and one which exports the service and revisions directly. However, the latter can not be applied directly to Kubernetes but only with a (still to build) `kn service import` as it needs to fix the `ownerReferences` (those can't be set from the outside).

The format suggested is:

```yaml
apiVersion: client.knative.dev/v1alpha1
kind: Export
meta: 
   exportDate: ....
   name: ....
kind:
   service: 
         ... // a full Knative service spec
   revisions:   // list of Knative revisions, in creation order
   - ....
```

Ideally, it should be registered in a schema, using the same machinery as for CRDs in order to leverage cli-runtime output formats.

For the option `--mode` I suggest a renaming to better reflect the purpose:

* `--mode replay` --- Create a replay list of Knative Services
* `--mode export` --- To specify this new format. Not sure about the value we might use a name that better fits the purpose.

The main motivation to use a dedicated export type is to make it crystal clear that one can not import a bunch of Service and its Revisions with standard k8s tooling.
