### ISSUE TITLE
Proposal: Knative Resource Validation through kn

### ISSUE THREAD

**Issue by danielhelfand** [knative/client#892]
### Feature request

The ability to use `kn` to validate Knative CRDs, but provide a more informative error message or visualization of where issues are found in a resource definition.

### Use case

Ability to more easily find the source of an error in a resource definition that provides more details than kubectl/the standard parsing library. Instead of the error response mentioned in https://github.com/knative/eventing/issues/2714, providing a line number where the error is occurring could be extremely helpful in figuring about why resource creations return errors. 

### UI Example

```
# Local file definition

$ kn validate file.yaml

Error: Error from server (BadRequest): error when creating "config/pingsource.yaml": admission webhook "webhook.eventing.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "apiVersion" on line 9

```

```
# Remote file definition with visual enhancement. Would have some way of highlighting the location of the error as opposed to printing the error like below.

$ kn validate www.github.com/repo/file.yaml --visual
```

```yaml
apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: ping
spec:
  schedule: "*/1 * * * *"
  jsonData: '{"msg": "hello"}'
  sink:
    apiVersion: v1 ERROR: unknown field "apiVersion" on line 9
    kind: Service
    name: event-display
```

/kind proposal
