### ISSUE TITLE
kn Tekton Task Isn't Executable As Script

### ISSUE THREAD

**Issue by danielhelfand** [knative/client#949]
### Bug report

Trying to use the [`kn` Tekton Task](https://github.com/tektoncd/catalog/tree/436f1e834734c053511ae38dd4f9e20e2888234f/task/kn/0.1) as a script in a step, such as below, fails with the error also shown below:

```
- name: ksvc-url
      image: "gcr.io/knative-releases/knative.dev/client/cmd/kn:latest"
      script: |
        kn service describe petclinic-ksvc -o url -n ns | tee $(results.url)
```

```
[ksvc-url] 2020/07/23 16:59:20 Error executing command: fork/exec /tekton/scripts/script-4-844l8: no such file or directory
```

Seems there is no bash for the image.

### Expected behavior

Able to execute `kn` in a Tekton step script. 

### Steps to reproduce the problem

Execute a simple Task with `kn`:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-version
  annotations:
    description: |
      A simple task that prints kn version
spec:
  results:
    - name: version
      description: kn version
  steps:
    - name: get-version
      image: "gcr.io/knative-releases/knative.dev/client/cmd/kn:latest"
      script: |
        kn version | tee /tekton/results/version
    - name: print-version
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        result=$(cat "$(results.version.path)")
        echo $result
```

**Comment by navidshaikh** [comment]
kn binary in image is present at `/ko-app/kn` and `/ko-app` dir isnt in $PATH. So the task should use absolute path of the kn binary. 

@danielhelfand : please re-try with
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-version
  annotations:
    description: |
      A simple task that prints kn version
spec:
  results:
    - name: version
      description: kn version
  steps:
    - name: get-version
      image: "gcr.io/knative-releases/knative.dev/client/cmd/kn:latest"
      script: |
        /ko-app/kn version | tee /tekton/results/version
    - name: print-version
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        result=$(cat "$(results.version.path)")
        echo $result
```

I am working on refining the kn task at catalog, will include an example using kn image with `script`.

Beside, I think `ko` should add `/ko-app` dir to $PATH if thats where the binaries go? @ImJasonH  wdyt?
